title: Chaotic Practices
description: Constant work in progress (such as life)
author:
  name: Pablo Rodríguez
  website: http://www.ousia.tk
lang: en
show.downloads: 0
theme: minima
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from